config/routes.rb
Rails.application.routes.draw do
  resources :stores, only: [:index, :show]
  resources :imports, only: [:index, :new, :create]
  root 'imports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import < ApplicationRecord
  validates_presence_of :name

  has_many :transactions
end

app/models/store.rb
class Store < ApplicationRecord
  validates_presence_of :name, :owner
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :store
  belongs_to :import

  validates_presence_of :hour, :date, :card_number, :transaction_type, :amount, :document

  def parsed_date
    Time.parse("#{date}#{hour}")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def index
    @imports = Import.all
  end

  def new
  end

  def create
    ImportCNAB.new(CNABParser.new(params[:file].path)).call
    redirect_to :imports
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.order(:id)
  end

  def show
    @store = Store.find(params[:id])
    @transactions = Transaction.where(store: @store)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/imports/create.html.erb
<h1>Import#create</h1>
<p>Find me in app/views/import/create.html.erb</p>

app/views/imports/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Numero de Transacções</th>
    </tr>
  </thead>
  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <th scope="row"><%= import.id %></th>
        <td><%= import.name  %></td>
        <td><%= import.transactions.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/imports/new.html.erb
<div class="row">
  <div class="col-4">
  </div>
  <div class="col-4">
    <h1>Importar novo arquivo</h1>
    <%= form_with url: "/imports", local: true  do |f| %>
      <div class="form-group">
        <%= f.file_field :file, class:'form-control-file' %>
        </br>
        </br>
        <%= f.submit "Importar", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-4">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ImpulsoCnabTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/">
        Teste Impulso 
      </a>
       <a  href="/stores">
        Lojas 
      </a>
      <a  href="/">
        <%= link_to 'Importar Novo Arquivo', new_import_path %>
      </a>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/stores/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Dono</th>
      <th scope="col">Saldo</th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <th scope="row"><%= link_to(store.id, store) %></th>
        <td><%= store.name  %></td>
        <td><%= store.owner %></td>
        <td class="text-<%= store.current_balance.positive? ? 'success' : 'danger'%>"><%= store.current_balance %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/show.html.erb
<table class="table">
  <thead>
  <tr>
      <th scope="col"><%= @store.name %></th>
    </tr>
    <tr>
      <th scope="col">#</th>
      <th scope="col">CPF do beneficiário</th>
      <th scope="col">Cartão</th>
      <th scope="col">Descrição</th>
      <th scope="col">Natureza</th>
      <th scope="col">Data</th>
      <th scope="col">Hora</th>
      <th scope="col">Sinal</th>
      <th scope="col">Valor</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
        <% operation_details = UpdateStoreCredits::TransactionOperationConverter.from_type(transaction.transaction_type) %>
      <tr>
        <th scope="row"><%= transaction.id %></th>
        <td><%= transaction.document  %></td>
        <td><%= transaction.card_number  %></td>
        <td><%= operation_details.description %></td>
        <td><%= operation_details.type %></td>
        <td><%= transaction.parsed_date.strftime("%d/%m/%Y") %></td>
        <td><%= transaction.parsed_date.strftime("%H:%M:%S") %></td>
        <td><%= operation_details.operator %></td>
        <td class="text-<%= operation_details.operator == "+" ? 'success' : 'danger'%>"><%= transaction.amount %></td>
      </tr>
    <% end %>
    <tr>
        <th colspan="8">Saldo</th>
        <td class="text-<%= @store.current_balance.positive? ? 'success' : 'danger'%>"><%= @store.current_balance %></td>
      </tr>
  </tbody>
</table>